spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mappings
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update  

logging:
  level:
   org:
    hibernate:
     SQL: DEBUG    
        
